# Generated by Django 2.2.6 on 2019-10-26 23:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('producto', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehiculo',
            name='vendido',
            field=models.BooleanField(default=False),
        ),
    ]
